// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/iamzhangxin/xuandu-gateway/internal/admin"
	"github.com/iamzhangxin/xuandu-gateway/internal/archiveidl"
	"github.com/iamzhangxin/xuandu-gateway/internal/config"
	"github.com/iamzhangxin/xuandu-gateway/internal/httpgateway"
	"github.com/iamzhangxin/xuandu-gateway/internal/mcp"
	"github.com/iamzhangxin/xuandu-gateway/internal/metadata"
	"github.com/iamzhangxin/xuandu-gateway/internal/runtime"
)

// Injectors from wire.go:

func Initialize(c *config.Config) (*App, error) {
	apiConfig := metadata.NewConsulConfig(c)
	consulStore, err := metadata.NewConsulStore(c, apiConfig)
	if err != nil {
		return nil, err
	}
	httpFetcher := archiveidl.NewFetcher()
	builder := runtime.NewBuilder(apiConfig)
	manager := runtime.NewManager()
	service := admin.NewService(consulStore, httpFetcher, builder, manager)
	handler := httpgateway.NewHandler(c, manager)
	dataServer := httpgateway.NewServer(c, handler, service)
	server := admin.NewServer(c, service)
	consulRepository, err := mcp.NewRepository(c, apiConfig)
	if err != nil {
		return nil, err
	}
	mcpService := mcp.NewService(c, consulRepository, consulStore, manager)
	app := New(service, dataServer, server, manager, mcpService)
	return app, nil
}
